# Generated by Django 5.0.1 on 2024-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveSmallIntegerField()),
                ('end', models.PositiveSmallIntegerField(default=None, null=True)),
                ('establishment', models.CharField(max_length=60)),
                ('first', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Database', 'Database'), ('Version control', 'Version control'), ('Cloud services and platforms', 'Cloud services and platforms'), ('Data Analysis', 'Data Analysis'), ('API tools', 'API tools'), ('Development environments', 'Development environments'), ('Currently Learning', 'Currently Learning'), ('Coming Next', 'Coming Next')], max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=50)),
                ('modal_image', models.ImageField(upload_to='images/')),
                ('modal_description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
