# Generated by Django 5.0.1 on 2024-02-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexskillset',
            name='last',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexskillset',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
